package sys.model.pacientes;
// Generated 11/04/2018 12:39:53 PM by Hibernate Tools 4.3.1


//import java.util.HashSet;
//import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Desviacion generated by hbm2java
 */
@Entity
@Table(name = "desviacion")
public class Desviacion  implements java.io.Serializable {


     private Integer id;
     private String desviacion;
     private String cierre;
     private String apertura;
     //private Set atms = new HashSet(0);

    public Desviacion() {
    }

	
    public Desviacion(String desviacion, String cierre, String apertura) {
        this.desviacion = desviacion;
        this.cierre = cierre;
        this.apertura = apertura;
    }
    /*
    public Desviacion(String desviacion, String cierre, String apertura, Set atms) {
       this.desviacion = desviacion;
       this.cierre = cierre;
       this.apertura = apertura;
       this.atms = atms;
    }*/
   
    @Id
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name = "desviacion")
    public String getDesviacion() {
        return this.desviacion;
    }
    
    public void setDesviacion(String desviacion) {
        this.desviacion = desviacion;
    }
    
    @Column(name = "cierre")
    public String getCierre() {
        return this.cierre;
    }
    
    public void setCierre(String cierre) {
        this.cierre = cierre;
    }
    
    @Column(name = "apertura")
    public String getApertura() {
        return this.apertura;
    }
    
    public void setApertura(String apertura) {
        this.apertura = apertura;
    }
    /*
    @Column(name = "atm")
    public Set getAtms() {
        return this.atms;
    }
    
    public void setAtms(Set atms) {
        this.atms = atms;
    }*/
}


