package sys.model.pacientes;
// Generated 11/04/2018 12:39:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * PlanTratamiento generated by hbm2java
 */

@Entity
@Table(name = "plan_tratamiento")
public class PlanTratamiento  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private Tratamientos tratamientos;
     private Date fecha;

    public PlanTratamiento() {
    }

    public PlanTratamiento(Paciente paciente, Tratamientos tratamientos, Date fecha) {
       this.paciente = paciente;
       this.tratamientos = tratamientos;
       this.fecha = fecha;
    }
   
    @Id
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name = "id_paciente")
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    
    @Column(name = "id_tratamiento")
    public Tratamientos getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Tratamientos tratamientos) {
        this.tratamientos = tratamientos;
    }
    
    @Column(name = "fecha")
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}


