package sys.model;
// Generated 14/10/2017 07:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


  private int matricula;
     private String nombreCompleto;
     private String semestre;
     private String grupo;
     private Set<ListaAlumnos> listaAlumnoses = new HashSet<ListaAlumnos>(0);
     private Set<BitacoraRecibos> bitacoraReciboses = new HashSet<BitacoraRecibos>(0);

    public Alumnos() {
    }

	
    public Alumnos(int matricula, String nombreCompleto) {
        this.matricula = matricula;
        this.nombreCompleto = nombreCompleto;
    }
    public Alumnos(int matricula, String nombreCompleto, String semestre, String grupo, Set<ListaAlumnos> listaAlumnoses, Set<BitacoraRecibos> bitacoraReciboses) {
       this.matricula = matricula;
       this.nombreCompleto = nombreCompleto;
       this.semestre = semestre;
       this.grupo = grupo;
       this.listaAlumnoses = listaAlumnoses;
       this.bitacoraReciboses = bitacoraReciboses;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Set<ListaAlumnos> getListaAlumnoses() {
        return this.listaAlumnoses;
    }
    
    public void setListaAlumnoses(Set<ListaAlumnos> listaAlumnoses) {
        this.listaAlumnoses = listaAlumnoses;
    }
    public Set<BitacoraRecibos> getBitacoraReciboses() {
        return this.bitacoraReciboses;
    }
    
    public void setBitacoraReciboses(Set<BitacoraRecibos> bitacoraReciboses) {
        this.bitacoraReciboses = bitacoraReciboses;
    }




}


