package sys.model;
// Generated 14/10/2017 07:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AreaTratamientos generated by hbm2java
 */
public class AreaTratamientos  implements java.io.Serializable {


     private Integer area;
     private String tratamiento;
     private Set<MenuTratamientos> menuTratamientoses = new HashSet<MenuTratamientos>(0);

    public AreaTratamientos() {
    }

    public AreaTratamientos(String tratamiento, Set<MenuTratamientos> menuTratamientoses) {
       this.tratamiento = tratamiento;
       this.menuTratamientoses = menuTratamientoses;
    }
   
    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public Set<MenuTratamientos> getMenuTratamientoses() {
        return this.menuTratamientoses;
    }
    
    public void setMenuTratamientoses(Set<MenuTratamientos> menuTratamientoses) {
        this.menuTratamientoses = menuTratamientoses;
    }




}


