package sys.model;
// Generated 22/10/2017 12:53:33 PM by Hibernate Tools 4.3.1

import sys.model.Alumnos;




/**
 * ListaAlumnos generated by hbm2java
 */
public class ListaAlumnos  implements java.io.Serializable {

   private Integer id;
     private Alumnos alumnos;
     private MaestroMaterias maestroMaterias;

    public ListaAlumnos() {
        alumnos = new Alumnos();
        maestroMaterias = new MaestroMaterias();
    }

    public ListaAlumnos(Alumnos alumnos, MaestroMaterias maestroMaterias) {
       this.alumnos = alumnos;
       this.maestroMaterias = maestroMaterias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public MaestroMaterias getMaestroMaterias() {
        return this.maestroMaterias;
    }
    
    public void setMaestroMaterias(MaestroMaterias maestroMaterias) {
        this.maestroMaterias = maestroMaterias;
    }





}


