package sys.model;
// Generated 22/10/2017 12:53:33 PM by Hibernate Tools 4.3.1

import sys.model.Alumnos;




/**
 * ListaAlumnos generated by hbm2java
 */
public class ListaAlumnos  implements java.io.Serializable {


     private Integer id;
     private Alumnos alumnos;
     private String clave;

    public ListaAlumnos() {
    }

	
    public ListaAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public ListaAlumnos(Alumnos alumnos, String clave) {
       this.alumnos = alumnos;
       this.clave = clave;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


