package sys.model;
// Generated 14/10/2017 07:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Maestro generated by hbm2java
 */
public class Maestro  implements java.io.Serializable {


     private int idEmpleado;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;
     private Set<MaestroMaterias> maestroMateriases = new HashSet<MaestroMaterias>(0);

    public Maestro() {
    }

	
    public Maestro(int idEmpleado, String nombre, String apellidoPaterno, String apellidoMaterno, String correo) {
        this.idEmpleado = idEmpleado;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correo = correo;
    }
    public Maestro(int idEmpleado, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, Set<MaestroMaterias> maestroMateriases) {
       this.idEmpleado = idEmpleado;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.maestroMateriases = maestroMateriases;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<MaestroMaterias> getMaestroMateriases() {
        return this.maestroMateriases;
    }
    
    public void setMaestroMateriases(Set<MaestroMaterias> maestroMateriases) {
        this.maestroMateriases = maestroMateriases;
    }




}


