package sys.model;
// Generated 14/10/2017 07:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer idMateria;
     private String materia;
     private int semestre;
     private Set<MaestroMaterias> maestroMateriases = new HashSet<MaestroMaterias>(0);

    public Materias() {
    }

	
    public Materias(String materia, int semestre) {
        this.materia = materia;
        this.semestre = semestre;
    }
    public Materias(String materia, int semestre, Set<MaestroMaterias> maestroMateriases) {
       this.materia = materia;
       this.semestre = semestre;
       this.maestroMateriases = maestroMateriases;
    }
   
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public int getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(int semestre) {
        this.semestre = semestre;
    }
    public Set<MaestroMaterias> getMaestroMateriases() {
        return this.maestroMateriases;
    }
    
    public void setMaestroMateriases(Set<MaestroMaterias> maestroMateriases) {
        this.maestroMateriases = maestroMateriases;
    }




}


